[project]
name = "fix-user-service"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "infrastructure @ file:///${PROJECT_ROOT}/../infrastructure",
    "asyncpg>=0.30.0",
    "environs>=14.2.0",
    "faststream[nats]>=0.5.43",
    "sqlalchemy>=2.0.41",
    "pydantic>=2.11.7",
]
